easy_admin:
    site_name: '<i class="fas fa-users-cog"></i> Administration'

    user:
        name_property_path: 'fullname'

    list:
        item_permission: ROLE_ADMIN
        actions:
            - { name: 'edit', icon: 'pencil', label: false }
            - { name: 'delete', icon: 'trash', label: false }

    design:
        menu:
            - { entity: 'Utilisateurs', icon: 'user', permission: 'ROLE_ADMIN' }
            - { entity: 'Comptes', permission: 'ROLE_ADMIN' }
            - { entity: 'Transactions', permission: 'ROLE_ADMIN' }
            - { entity: 'Cartes', permission: 'ROLE_ADMIN' }
            - { entity: 'Terminaux', permission: ['ROLE_ADMIN', 'ROLE_SHOP'] }

    entities:
        Utilisateurs:
            controller: App\Controller\Admin\UserManagerController
            class: App\Entity\User
            disabled_actions: ['delete']
            list:
                item_permission: ROLE_ADMIN
                fields:
                    - id
                    - { property: 'name', label: 'Nom' }
                    - { property: 'surname', label: 'Prénom' }
                    - { property: 'username', label: 'Pseudo' }
                    - { property: 'email', label: 'Contact' }
                    - { property: 'banned', label: 'Banni' }
                    - { property: 'roles', label: 'Roles' }
            form:
                title: Créer ou Modifier un utilisateur
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'surname', label: 'Prénom' }
                    - { property: 'username', label: 'Pseudo' }
                    - { property: 'email', label: 'Contact' }
                    - { property: 'roles', label: 'Roles' }
            new:
                item_permission: 'ROLE_ADMIN'

        Comptes:
            class: App\Entity\Account
            controller: App\Controller\Admin\AccountManagerController
            disabled_actions: ['delete']
            list:
                item_permission: ROLE_ADMIN
                fields:
                    - id
                    - { property: 'iduser', label: 'No Client' }
                    - { property: 'label', label: 'Type de compte' }
            form:
                title: Création ou Modification d'un Compte
                fields:
                    - { property: 'iduser', label: 'No Client' }
                    - { property: 'label', label: 'Type de compte' }
            new:
                item_permission: 'ROLE_ADMIN'
        Cartes:
            class: App\Entity\Card
            list:
                item_permission: ROLE_ADMIN
                fields:
                    - id
                    - { property: 'uid', label: 'No Carte' }
                    - { property: 'account_id', label: 'No Compte' }
            form:
                title: Ajout ou Modification d'une Carte
            new:
                item_permission: 'ROLE_ADMIN'

        Terminaux:
            class: App\Entity\Terminal
            controller: App\Controller\Admin\TerminalManagerController
            disabled_actions: ['edit']
            list:
                item_permission: [ROLE_ADMIN, ROLE_SHOP]
                fields:
                    - { property: 'id', permission: 'ROLE_ADMIN' }
                    - ip
                    - { property: 'idAccount', label: 'No Compte' }
            form:
                title: Ajout d'un Terminal
                fields:
                    - ip
                    - { property: 'idAccount', label: 'No Compte', permission: "ROLE_ADMIN" }

        Transactions:
            class: App\Entity\Transaction
            controller: App\Controller\Admin\TransactionManagerController
            disabled_actions: ['edit', 'delete']
            list:
                item_permission: ROLE_ADMIN
                fields:
                    - { property: 'hash', label: 'Code' }
                    - { property: 'type', label: 'Type' }
                    - { property: 'amount', label: 'Montant' }
                    - { property: 'idissuer', label: 'No Client Emetteur' }
                    - { property: 'idreceiver', label: 'No Client Receveur' }
                    - { property: 'label', label: 'Intitulé' }
                    - date
            form:
                fields:
                    - { property: 'amount', label: 'Montant' }
                    - { property: 'idreceiver', label: 'No Client Receveur' }
                    - { property: 'label', label: 'Intitulé' }
            new:
                item_permission: 'ROLE_ADMIN'