easy_admin:
    site_name: '<i class="fas fa-users-cog"></i> Administration'

    user:
        name_property_path: 'fullname'

    list:
        actions:
            - { name: 'edit', icon: 'pencil', label: false }
            - { name: 'delete', icon: 'trash', label: false }

    design:
        menu:
            - { entity: 'Utilisateurs', permissions: 'ROLE_ADMIN' }
            - { entity: 'Comptes', permissions: 'ROLE_ADMIN' }
            - { entity: 'Transactions', permissions: 'ROLE_ADMIN' }
            - { entity: 'Cartes', permissions: 'ROLE_ADMIN' }
            - { entity: 'Terminaux', permissions: 'ROLE_ADMIN' }

    entities:
        Utilisateurs:
            controller: App\Controller\Admin\UserManagerController
            class: App\Entity\User
            list:
                fields:
                    - id
                    - { property: 'name', label: 'Nom' }
                    - { property: 'surname', label: 'Prénom' }
                    - { property: 'username', label: 'Pseudo' }
                    - { property: 'email', label: 'Contact' }
                    - { property: 'banned', label: 'Banni' }
                    - { property: 'roles', label: 'Roles' }
            form:
                title: Créer ou Modifier un utilisateur
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'surname', label: 'Prénom' }
                    - { property: 'username', label: 'Pseudo' }
                    - { property: 'email', label: 'Contact' }
                    - { property: 'roles', label: 'Roles' }

        Comptes:
            class: App\Entity\Account
            controller: App\Controller\Admin\AccountManagerController
            list:
                fields:
                    - id
                    - { property: 'iduser', label: 'No Client' }
                    - { property: 'label', label: 'Type de compte' }
            form:
                title: Création ou Modification d'un Compte
                fields:
                    - { property: 'iduser', label: 'No Client' }
                    - { property: 'label', label: 'Type de compte' }

        Cartes:
            class: App\Entity\Card
            list:
                fields:
                    - id
                    - { property: 'uid', label: 'No Client' }
                    - { property: 'account_id', label: 'No Compte' }
            form:
                title: Ajout ou Modification d'une Carte

        Terminaux:
            class: App\Entity\Terminal
            list:
                fields:
                    - id
                    - ip
                    - { property: 'idAccount', label: 'No Compte' }
            form:
                title: Ajout ou Modification d'un Terminal
                fields:
                    - ip
                    - { property: 'idAccount', label: 'No Compte' }

        Transactions:
            class: App\Entity\Transaction
            disabled_actions: ['edit', 'delete']
            list:
                fields:
                    - { property: 'hash', label: 'Code' }
                    - { property: 'type', label: 'Type' }
                    - { property: 'amount', label: 'Montant' }
                    - { property: 'idissuer', label: 'No Client Emetteur' }
                    - { property: 'idreceiver', label: 'No Client Receveur' }
                    - { property: 'label', label: 'Intitulé' }
                    - date
            form:
                fields:
                    - { property: 'type', label: 'Type' }
                    - { property: 'amount', label: 'Montant' }
                    - { property: 'idreceiver', label: 'No Client Receveur' }
                    - { property: 'label', label: 'Intitulé' }
