easy_admin:
    entities:
        Utilisateurs:
            class: App\Entity\User
            list:
                fields:
                    - id
                    - { property: 'name', label: 'Nom' }
                    - { property: 'surname', label: 'Prénom' }
                    - { property: 'username', label: 'Pseudo' }
                    - { property: 'email', label: 'Contact' }
                    - { property: 'banned', label: 'Banni' }
                    - { property: 'roles', label: 'Roles' }

        Comptes:
            class: App\Entity\Account
            list:
                fields:
                    - id
                    - { property: 'iduser', label: 'No Client' }
                    - { property: 'label', label: 'Type de compte' }

        Cartes:
            class: App\Entity\Card
            list:
                fields:
                    - id
                    - { property: 'uid', label: 'No Client' }
                    - { property: 'account_id', label: 'No Compte' }

        Terminaux:
            class: App\Entity\Terminal
            list:
                fields:
                    - id
                    - ip
                    - { property: 'idAccount', label: 'No Compte' }
        Transactions:
            class: App\Entity\Transaction
            list:
                fields:
                    - id
                    - { property: 'type', label: 'Type' }
                    - { property: 'amount', label: 'Montant' }
                    - { property: 'idissuer', label: 'No Client Emetteur' }
                    - { property: 'idreceiver', label: 'No Client Receveur' }
                    - { property: 'label', label: 'Intitulé' }
